name: 'Setup Noraneko Build Environment'
description: 'Sets up Node.js, Deno, and installs Noraneko dependencies'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Install Noraneko dependencies
      run: deno install --allow-scripts
      shell: bash
      working-directory: ${{ github.workspace }}/noraneko
